# Generated by Django 6.0.4 on 2026-04-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sample_size',
        ),
        migrations.AddField(
            model_name='profile',
            name='country_name',
            field=models.CharField(default='Nigeria', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='country_id',
            field=models.CharField(max_length=2),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['gender'], name='api_profile_gender_8edb79_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['country_id'], name='api_profile_country_65dc5e_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age'], name='api_profile_age_d97b9b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['age_group'], name='api_profile_age_gro_f7046d_idx'),
        ),
    ]
